[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
PORT = "5000"
FLASK_ENV = "production"

[[services.ports]]
port = 5000

[services.build]
builder = "nixpacks"

[services.deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --max-requests 1000 --max-requests-jitter 100 app:app"